### ISSUE TITLE
parse_log.py error

### ISSUE THREAD

**Issue by mahilaMoghadami** [HC-Guo/LogFormer#4]
hello
thanks for implementation sharing
I use BGL dataset but I get this error while Im using pars3_log.py file:

I download BGL dataset in link which you shared: https://github.com/logpai/loghub
 
Parsing file: /content/drive/MyDrive/LogDataset/BGL/BGL.log
Processed 100.0% of log lines.
Traceback (most recent call last):
  File "/content/LogFormer/parse_log.py", line 42, in <module>
    parser.parse(log_file)
  File "/content/LogFormer/Drain.py", line 285, in parse
    self.outputResult(logCluL)
  File "/content/LogFormer/Drain.py", line 216, in outputResult
    self.df_log["ParameterList"] = self.df_log.apply(self.get_parameter_list, axis=1) 
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 9423, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/apply.py", line 678, in apply
    return self.apply_standard()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/apply.py", line 798, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/apply.py", line 814, in apply_series_generator
    results[i] = self.f(v)
  File "/content/LogFormer/Drain.py", line 339, in get_parameter_list
    template_regex = re.sub(r'\\ +', r'\s+', template_regex)
  File "/usr/local/lib/python3.10/dist-packages/regex/regex.py", line 278, in sub
    return pat.sub(repl, string, count, pos, endpos, concurrent, timeout)
  File "/usr/local/lib/python3.10/dist-packages/regex/regex.py", line 706, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
  File "/usr/local/lib/python3.10/dist-packages/regex/_regex_core.py", line 1730, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \s at position 2

![image](https://github.com/HC-Guo/LogFormer/assets/52579373/69f9b504-34a7-4c49-b705-bc2380222256)

appreciate your help.

**Comment by fmy112** [comment]
me too，how to solve

**Comment by Kenscofield** [comment]
Me too. 
Please help.
